on:
  push:
    branches:
      - dev
name: 🚀 Deploy website on push to dev branch
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-interaction
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: geoprecisegroup.com
        username: ${{ secrets.GEOPRECISE_FTP_USERNAME }}
        password: ${{ secrets.GEOPRECISE_FTP_PASSWORD }}
        server-dir: test.geoprecisegroup.com